basePath: /api/v1
definitions:
  catschemas.TGetCat:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  catschemas.TPostCat:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
  description: This is a backend server for the template project
  termsOfService: http://swagger.io/terms/
  title: Template API documentation
  version: "1.0"
paths:
  /cat:
    get:
      consumes:
      - application/json
      description: Retrieve all cat information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/catschemas.TGetCat'
            type: array
      security:
      - BearerAuth: []
      summary: Get all cat
      tags:
      - Cat
    post:
      consumes:
      - application/json
      description: Post a cat
      parameters:
      - description: Cat information
        in: body
        name: cat
        required: true
        schema:
          $ref: '#/definitions/catschemas.TPostCat'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/catschemas.TGetCat'
      security:
      - BearerAuth: []
      summary: Post a cat
      tags:
      - Cat
  /cat/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a cat
      parameters:
      - description: Cat ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Delete a cat
      tags:
      - Cat
    get:
      consumes:
      - application/json
      description: Retrieve a cat information
      parameters:
      - description: Cat ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/catschemas.TGetCat'
      security:
      - BearerAuth: []
      summary: Get a cat
      tags:
      - Cat
    put:
      consumes:
      - application/json
      description: Update a cat
      parameters:
      - description: Cat ID
        in: path
        name: id
        required: true
        type: string
      - description: Cat information
        in: body
        name: cat
        required: true
        schema:
          $ref: '#/definitions/catschemas.TPostCat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/catschemas.TGetCat'
      security:
      - BearerAuth: []
      summary: Update a cat
      tags:
      - Cat
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
